language: java
sudo: required
dist: trusty

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarqube:
    organization: "juncevich-github"
    token:
      secure: $SONAR_TOKEN
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - ./gradlew sonarqube
  
  
after_script:
  - docker-compose down
jdk:
  - oraclejdk8


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
notifications:
    email:
      - a.juncevich@gmail.com
