language: java
sudo: required
script:
  - docker-compose up
install: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarqube:
    organization: "juncevich-github"
    token:
      secure: $SONAR_TOKEN
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - ./gradlew sonarqube
jdk:
  - oraclejdk8


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
notifications:
    email:
      - a.juncevich@gmail.com
